volumes:
  base-data:
  db-data:
  redis-data:
services:
  db:
    image: postgres:18
    env_file:
      - .env
    restart: always
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

  fastapi-base:
    restart: always
    env_file:
      - .env
    build:
      context: ./fastapi-base
      dockerfile: ./Dockerfile
      args:
        env: ${ENV}
    ports:
      - "8666:8000"
    command: |
      bash -c "
      gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --log-level=debug --timeout=60 --reload"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - base-data:/data
      - ./fastapi-base/src:/code/src
      - ./fastapi-base/tests:/code/tests
      - ./fastapi-base/alembic.ini:/code/alembic.ini
      - ./fastapi-base/logconfig.yml:/code/logconfig.yml
  redis:
    restart: always
    image: redis:7-alpine
    volumes:
      - redis-data:/data
  celery:
    restart: always
    build: ./fastapi-base
    command: celery --app=src worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - fastapi-base
      - redis
  beat:
    restart: always
    build: ./fastapi-base
    command: celery --app=src beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - fastapi-base
      - redis
